- hosts: all
  connection: local
  strategy: free
  gather_facts: false
  vars:
    repo_ansible_base_path: "{{ lookup('env', 'REPO_ANSIBLE_BASE_PATH') or (playbook_dir + '/workspace') }}"
    repo_path: "{{ repo_ansible_base_path }}/{{ inventory_hostname }}"
  tasks:
    - import_tasks: tasks/load-data.yaml

    - import_tasks: tasks/pull-request.yaml
