- hosts: all
  strategy: free
  gather_facts: false
  connection: local
  vars:
    repo_ansible_base_path: "{{ lookup('env', 'REPO_ANSIBLE_BASE_PATH') }}"
  tasks:
    - fail:
        msg: 'REPO_ANSIBLE_BATH_PATH environment variable must be defined'
      when: repo_ansible_base_path == ''

    - name: "repository checkout"
      ansible.builtin.git:
        repo: "git@github.com:linkorb/{{ inventory_hostname }}.git"
        dest: "{{ repo_ansible_base_path }}/{{ inventory_hostname }}"
        force: true
        depth: 1
