- hosts: all
  connection: local
  strategy: free
  gather_facts: false
  vars:
    repo_ansible_base_path: "{{ lookup('env', 'REPO_ANSIBLE_BASE_PATH') or (playbook_dir + '/workspace') }}"
  tasks:
    - import_tasks: tasks/checkout.yaml
      vars:
        repository: "{{ inventory_hostname }}"
