- name: Apply repo php-qa standards
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_managed: 'Ansible managed'

  tasks:
    - name: Include task foo
      include_tasks: set_facts.yaml
    
    - name: Generate .php-cs-fixer.dist.php file
      ansible.builtin.template:
        src: "{{ './templates/php-qa/php-cs-fixer.dist.php.j2' }}"
        dest: "{{ repo.path + '/.php-cs-fixer.dist.php' }}"
    
    - name: Generate phpstan.neon file
      ansible.builtin.template:
        src: "{{ './templates/php-qa/phpstan.neon.j2' }}"
        dest: "{{ repo.path + '/phpstan.neon' }}"

    - name: Generate reviewdog.yaml file
      ansible.builtin.template:
        src: "{{ './templates/php-qa/reviewdog.yaml.j2' }}"
        dest: "{{ repo.path + '/.reviewdog.yaml' }}"
      
    - name: Append file name to .gitignore
      lineinfile:
        path: "{{ repo.path + '/.gitignore' }}"
        line: "{{ item }}"
      with_items:
        - .php-cs-fixer.cache
