- hosts: all
  connection: local
  strategy: free
  gather_facts: false
  vars:
    base_path: "{{ lookup('env', 'REPO_ANSIBLE_BASE_PATH') or (playbook_dir + '/workspace') }}"
    repo_path: "{{ base_path }}/{{ inventory_hostname }}"
  tasks:
    - name: generate repo.yaml if missing
      ansible.builtin.command: "./generate_repo_yaml.py {{ repo_path }}/repo.yaml"
      register: generate_repo
      changed_when: "'skipped' not in generate_repo.stdout"
