- hosts: all
  connection: local
  strategy: free
  gather_facts: false
  vars:
    repo_ansible_base_path: "{{ lookup('env', 'REPO_ANSIBLE_BASE_PATH') or (playbook_dir + '/workspace') }}"
    changes: "{{ lookup('env', 'REPO_ANSIBLE_CHANGES') }}"
    repo_path: "{{ repo_ansible_base_path }}/{{ inventory_hostname }}"
  tasks:
    - import_tasks: tasks/checkout.yaml
      vars:
        repository: "{{ inventory_hostname }}"

    - import_tasks: tasks/load-data.yaml

    - import_tasks: tasks/generate-files.yaml

    - import_tasks: tasks/devcontainer.yaml

    - import_tasks: tasks/husky.yaml

    - import_tasks: tasks/helm.yaml
      when: repo.type == 'application'

    - import_tasks: tasks/php-qa.yaml
      when: false
      #when: repo.type in ['application','library','symfony-bundle']

    - import_tasks: tasks/pull-request.yaml
      when: changes == 'pull-request'
