- hosts: all
  strategy: free
  gather_facts: false
  connection: local
  tasks:
    - name: "repository checkout"
      ansible.builtin.git:
        repo: "git@github.com:linkorb/{{ inventory_hostname }}.git"
        dest: "./workspace/{{ inventory_hostname }}"
        force: true

- ansible.builtin.import_playbook: playbook-apply.yaml
  vars:
    repo_path: "./workspace/{{ inventory_hostname }}"
