- hosts: localhost
  connection: local
  vars:
    repo_path: "{{ lookup('env', 'PWD') }}"
  tasks:

    - import_tasks: tasks/retrieve-validate-repo-data.yaml
    - import_tasks: tasks/retrieve-docs-data.yaml
    - import_tasks: tasks/generate-files.yaml

    - name: Execute application-specific tasks
      block:
      - import_tasks: tasks/husky.yaml
      - import_tasks: tasks/helm.yaml
      when:
        - repo.type in ['application']

    - name: Execute tasks for applications, libraries, and symfony-bundles
      block:
      - import_tasks: tasks/devcontainer.yaml
      - import_tasks: tasks/other-dev-generated-files.yaml
      when:
        - repo.type in ['application', 'library', 'symfony-bundle']

    - name: Execute tasks for PHP application, libraries, and symfony-bundles
      block:
        - import_tasks: tasks/php-qa.yaml
      when:
        - repo.type in ['application', 'library', 'symfony-bundle']
