- hosts: localhost
  connection: local
  vars:
    repo_path: "{{ lookup('env', 'PWD') }}"
  tasks:
    - import_tasks: tasks/load-data.yaml

    - import_tasks: tasks/generate-files.yaml

    - import_tasks: tasks/devcontainer.yaml

    - import_tasks: tasks/husky.yaml

    - import_tasks: tasks/helm.yaml
      when: repo.type == 'application'

    - import_tasks: tasks/php-qa.yaml
      when: repo.type in ['application','library','symfony-bundle']
