- name: "repository checkout"
  ansible.builtin.git:
    repo: "git@github.com:{{ organization if organization is defined else 'linkorb' }}/{{ repository }}.git"
    dest: "{{ destination }}"
    force: true
    depth: 1
# organization variable, useful if the changes in bulk need to be applied to a specific fork instead of the upstream
# linkorb owned repository. During playbook testing useful for auto-push/pull-request scenario testing.
