- name: Creates .husky/ directories
  ansible.builtin.file:
    path: "{{ repo_path + item.name }}"
    state: directory
  loop:
    - { name: '/.husky' }
    - { name: '/.husky/_' }

- name: Write .husky/_/husky.sh
  ansible.builtin.copy:
    src: "{{ './templates/husky/husky.sh' }}"
    dest: "{{ repo_path + '/.husky/_/husky.sh' }}"
    mode: a+x

- name: generate .husky/commit-msg
  ansible.builtin.template:
    src: "{{ './templates/husky/commit-msg.j2' }}"
    dest: "{{ repo_path + '/.husky/commit-msg' }}"
    mode: a+x

- name: generate commitlint.config.js
  ansible.builtin.template:
    src: "{{ './templates/husky/commitlint.config.js.j2' }}"
    dest: "{{ repo_path + '/commitlint.config.js' }}"
