- when: repo.github.features.sdlc_workflows
  block:
  - name: copy semantic-release .releaserc file
    ansible.builtin.copy:
      src: ./templates/.releaserc
      dest: "{{ repo_path }}/.releaserc"

  - name: find workflow extensions
    ansible.builtin.command: "./library/list_extension_workflows.py '{{ repo_path }}'"
    register: extension_workflows
    changed_when: false

  - name: define followup_workflows
    set_fact:
      followup_workflows: "{{ extension_workflows.stdout | from_json }}"

  - name: copy github actions workflow files
    ansible.builtin.template:
      src: "./templates/.github/workflows/{{ item.target }}.j2"
      dest: "{{ repo_path + '/.github/workflows/' + item.target }}"
      variable_start_string: '[['
      variable_end_string: ']]'
    vars:
      - workflow_group: "{{ item.workflow_group }}"
    loop:
      - target: 00-start.yaml
        workflow_group: ""
      - target: 10-review.yaml
        workflow_group: "10"
      - target: 30-release-and-build.yaml
        workflow_group: "30"
      - target: 40-helm.yaml
        workflow_group: "40"
      - target: 50-security.yaml
        workflow_group: "50"
      - target: 90-cleanup.yaml
        workflow_group: "90"

- name: generate .dockerignore
  ansible.builtin.template:
    src: ./templates/.dockerignore.j2
    dest: "{{ repo_path }}/.dockerignore"

- name: generate .editorconfig
  ansible.builtin.template:
    src: ./templates/.editorconfig.j2
    dest: "{{ repo_path }}/.editorconfig"
