# {{ repo_managed }}
name: Helm Publish

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      new-release-published:
        required: true
        type: string
      release-version:
        required: true
        type: string

jobs:
  helm:
    if: inputs.new-release-published == 'true'
    runs-on: self-hosted

    steps:
    - name: GitHub Environment Variables Action
      uses: FranzDiebold/github-env-vars-action@v2

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: "helm-chart"

    - name: Install Helm
      if: steps.check_files.outputs.files_exists == 'true'
      uses: azure/setup-helm@v3

    - name: Output release
      if: steps.check_files.outputs.files_exists == 'true'
      run: "echo ${{ inputs.release-version }}"

    - name: Set Chart.yaml version to release-version
      if: steps.check_files.outputs.files_exists == 'true'
      run: "sed -i s/chartversionplaceholder/${{ inputs.release-version }}/ helm-chart/Chart.yaml"

    - name: Set Chart.yaml appVersion to release-version
      if: steps.check_files.outputs.files_exists == 'true'
      run: "sed -i s/appversionplaceholder/${{ inputs.release-version }}/ helm-chart/Chart.yaml"

    - name: Add Bitnami Helm repo
      if: steps.check_files.outputs.files_exists == 'true'
      run: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Update Helm repos
      if: steps.check_files.outputs.files_exists == 'true'
      run: helm repo update

    - name: Install dependencies for Helm chart
      if: steps.check_files.outputs.files_exists == 'true'
      continue-on-error: true
      run: cd helm-chart && helm dependency update

    - name: Package Helm chart
      if: steps.check_files.outputs.files_exists == 'true'
      run: helm package helm-chart/

    - name: Upload packaged Chart - if this fails give repo permission to chartmuseum-pass org variable
      if: steps.check_files.outputs.files_exists == 'true'
      continue-on-error: true
      run: curl --silent --fail --show-error -u "github:${{ secrets.CHARTMUSEUMPASS }}" --data-binary "@`ls -1 *.tgz | head -n1`" https://charts.linkorb.com/api/charts
