- name: remove do-all 00-start.yaml workflow file
  ansible.builtin.file:
    path: "{{ repo_path }}/{{ item }}"
    state: absent
  loop:
    - .github/workflows/00-start.yaml
    - .github/workflows/dependabot-auto-merge.yaml
    - .github/workflows/repo-ansible.yaml
