name: Auto-update README.md

on:
  push:
    branches:
      - main
    paths:
      - 'repo.schema.yaml'
      - 'docs/partials/**.md'

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # XXX ansible installed within GitHub Runner via pipx, which doesn't support direct installation from a file
      # like pip does. See https://github.com/pypa/pipx/issues/934
      - name: install repo-ansible dependencies
        run: cat requirements.txt | xargs pipx inject ansible-core

      - name: generate schema README table (markdown partial)
        run: python3 library/schema_to_docs_partial.py

      - name: run ansible playbook
        run: ansible-playbook playbook-cwd.yaml
        env:
          ANSIBLE_DISPLAY_OK_HOSTS: 0
          ANSIBLE_DISPLAY_SKIPPED_HOSTS: 0

      - name: commit README.md changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          if git commit -m "chore: auto-update README.md"; then
            git push
          fi
